Update competency_questions.md
NFDI4Chem/VibrationalSpectroscopyOntology pull request #63
Opened 2023-02-27 10:42 UTC by Zack-83

2023-02-27 10:49 UTC, Zack-83 commented on docs/competency_questions.md
```suggestion

* Find me which is a safe range of incoming laser powers to perform Raman experiments at wavelength Z on probe XY.

```

2023-02-27 10:52 UTC, Zack-83 commented on docs/competency_questions.md
```suggestion

* Find me a suitable solvent which is compatible with sample XY, i.e. which does not have any Raman peak or band between wavenumbers W1 and W2.

```

2023-03-14 09:40 UTC, StroemPhi requested changes
The comments about the competency questions should be deleted from the docs.

2023-03-14 09:40 UTC, StroemPhi commented on docs/competency_questions.md
> +> Requires to clarify the hierarchy in the ontology: e.g. experiment < investigation < project
But to answer it here, we do import OBI:0000011 (planned process) which is mapped to ISAs investigation and OBI:0000066 (investigation) is mapped to ISAs study (see our [Raman spectroscopy T-Box.drawio](https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/blob/main/docs/images/Raman%20spectroscopy%20T-Box.drawio)). So with VIBSO we could currently state that an example Ramans spectroscopy assay is the part of an anonymous ISA study (OBI:0000066), which is part of a specific DGF funded project (ISA investigation / OBI planned process) and which has an information content entity as output that is about the assay :


```
example_db:RamanSpecAssay1  rdf:type      CHMO:0000663 (confocal Raman spectroscopy) ;
                            BFO:0000050 (part of)       [ rdf:type     OBI:0000066 ;
                                                          BFO:0000050 https://gepris.dfg.de/gepris/projekt/247890164 ;
                                                          OBI:0000299 (has_specified_output)       https://doi.org/10.1002/jrs.6482 ] .            
https://doi.org/10.1002/jrs.6482   IAO:0000136 (is about)   example_db:RamanSpecAssay1.
```

2023-03-14 09:46 UTC, StroemPhi commented on docs/competency_questions.md
> +> Somehow redundant with the following one; "what protocol" meaningful only within a workgroup
So I guess this question should best be changed just to: "What devices were used?"

2023-03-14 09:51 UTC, Zack-83 commented on docs/competency_questions.md
> +> Requires to clarify the hierarchy in the ontology: e.g. experiment < investigation < project
```suggestion
```

2023-03-14 09:51 UTC, Zack-83 commented on docs/competency_questions.md
> +> Somehow redundant with the following one; "what protocol" meaningful only within a workgroup
```suggestion
```

2023-03-14 09:52 UTC, Zack-83 commented on docs/competency_questions.md
> + ~* What protocol and devices were used?~
```suggestion
 * What devices were used?
```

2023-03-14 09:52 UTC, Zack-83 commented on docs/competency_questions.md
> + > It is more probable that the users document the names of the co-authors than the academic degree / role
```suggestion
```

2023-03-14 09:57 UTC, StroemPhi approved these changes

2023-03-14 09:58 UTC, merged